apiVersion: v1
kind: Service
metadata:
  name: pythonservice
  labels:
    app: pythonservice
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      nodePort: 30002
  selector:
    app : {{ .Values.deployment.label }}